hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/restart_server.sh
      timeout: 300
      runas: root
      
branch_config:
  master:
    deploymentGroupName: production
    deploymentConfig:
      autoRollbackConfiguration:
        enabled: true