// User action types
export const LOAD_USER = "LOAD_USER";
export const LOGOUT_USER = "LOGOUT_USER";

// Note action types
export const FETCH_NOTES = "FETCH_NOTES";
export const FETCH_NOTES_SUCCESS = "FETCH_NOTES_SUCCESS";
export const FETCH_NOTES_ERROR = "FETCH_NOTES_SUCCESS";
export const CREATE_NOTE = "CREATE_NOTE";
export const CREATE_NOTE_SUCCESS = "CREATE_NOTE_SUCCESS";
export const CREATE_NOTE_ERROR = "CREATE_NOTE_ERROR";
export const DELETE_NOTE = "DELETE_NOTE";
export const DELETE_NOTE_SUCCESS = "DELETE_NOTE_SUCCESS";
export const DELETE_NOTE_ERROR = "DELETE_NOTE_ERROR";
export const SWITCH_CURRENT_NOTE = "SWITCH_CURRENT_NOTE";
export const FINISH_SWITCHING = "FINISH_SWITCHING";
export const EDIT_CURRENT_NOTE_TITLE = "EDIT_CURRENT_NOTE_TITLE";
export const EDIT_CURRENT_NOTE_BODY = "EDIT_CURRENT_NOTE_BODY";
export const SAVE_TO_DATABASE = "SAVE_TO_DATABASE";
export const SAVE_TO_DATABASE_SUCCESS = "SAVE_TO_DATABASE_SUCCESS";
export const SAVE_TO_DATABASE_ERROR = "SAVE_TO_DATABASE_ERROR";
export const SEARCH = "SEARCH";
export const SEARCH_SUCCESS = "SEARCH_SUCCESS";
export const SEARCH_ERROR = "SEARCH_ERROR";
export const EXIT_SEARCH = "EXIT_SEARCH";
export const ADD_TAG = "ADD_TAG";
export const ADD_TAG_SUCCESS = "ADD_TAG_SUCCESS";
export const ADD_TAG_ERROR = "ADD_TAG_ERROR";
export const REMOVE_TAG = "REMOVE_TAG";
export const REMOVE_TAG_SUCCESS = "REMOVE_TAG_SUCCESS";
export const REMOVE_TAG_ERROR = "REMOVE_TAG_ERROR";
export const CHANGE_CATEGORY = "CHANGE_CATEGORY";
export const CHANGE_CATEGORY_SUCCESS = "CHANGE_CATEGORY_SUCCESS";
export const CHANGE_CATEGORY_ERROR = "CHANGE_CATEGORY_ERROR";

// Tag action types
export const FETCH_TAGS = "FETCH_TAGS";
export const FETCH_TAGS_SUCCESS = "FETCH_TAGS_SUCCESS";
export const FETCH_TAGS_ERROR = "FETCH_TAGS_ERROR";
export const CREATE_TAG = "CREATE_TAG";
export const CREATE_TAG_SUCCESS = "CREATE_TAG_SUCCESS";
export const CREATE_TAG_ERROR = "CREATE_TAG_ERROR";
